/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PonyMarquee {
        "autoDetection": boolean;
        "delay": number;
        "direction": 'ltr' | 'rtl';
        "gutter": number;
        "loop": number;
        "pauseOnHover": boolean;
        "speed": number;
        "text": string;
    }
}
declare global {
    interface HTMLPonyMarqueeElement extends Components.PonyMarquee, HTMLStencilElement {
    }
    var HTMLPonyMarqueeElement: {
        prototype: HTMLPonyMarqueeElement;
        new (): HTMLPonyMarqueeElement;
    };
    interface HTMLElementTagNameMap {
        "pony-marquee": HTMLPonyMarqueeElement;
    }
}
declare namespace LocalJSX {
    interface PonyMarquee {
        "autoDetection"?: boolean;
        "delay"?: number;
        "direction"?: 'ltr' | 'rtl';
        "gutter"?: number;
        "loop"?: number;
        "pauseOnHover"?: boolean;
        "speed"?: number;
        "text"?: string;
    }
    interface IntrinsicElements {
        "pony-marquee": PonyMarquee;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pony-marquee": LocalJSX.PonyMarquee & JSXBase.HTMLAttributes<HTMLPonyMarqueeElement>;
        }
    }
}
