/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PonyMarquee {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLPonyMarqueeElement extends Components.PonyMarquee, HTMLStencilElement {
    }
    var HTMLPonyMarqueeElement: {
        prototype: HTMLPonyMarqueeElement;
        new (): HTMLPonyMarqueeElement;
    };
    interface HTMLElementTagNameMap {
        "pony-marquee": HTMLPonyMarqueeElement;
    }
}
declare namespace LocalJSX {
    interface PonyMarquee {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "pony-marquee": PonyMarquee;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pony-marquee": LocalJSX.PonyMarquee & JSXBase.HTMLAttributes<HTMLPonyMarqueeElement>;
        }
    }
}
